### ISSUE TITLE
xkb

### ISSUE THREAD

**Issue by iandoug** [jnz1g/colejak#1]
Hi

Just curious ... the way you add it to xkb ... what happens when xkb gets updated?

I stuck my own layout in symbols/us but every update wipes that and the base/evdev files... so looking for "permanent" solution ....

**Comment by james-orcales** [comment]
When you place it under `$XDG_CONFIG_HOME/xkb`, it shouldn't be wiped out. Are you perhaps editing `/etc/share/X11/xkb/symbols/us`?

**Comment by iandoug** [comment]
> When you place it under `$XDG_CONFIG_HOME/xkb`, it shouldn't be wiped out. Are you perhaps editing `/etc/share/X11/xkb/symbols/us`?

Yes. What should $XDG_CONFIG_HOME be set to?
echo $XDG_CONFIG_HOME prints nothing.

Thanks, Ian

**Comment by james-orcales** [comment]
When `$XDG_CONFIG_HOME` is not set, xkb looks inside `$HOME/.config/xkb` instead.

**[Optional]** You can set `$XDG_CONFIG_HOME` to whatever path if you want a custom `.config` directory path. Xkb would then look inside `$XDG_CONFIG_HOME/xkb`

You can take a look at my previous layout, [KCX Qwerty](https://github.com/amesaine/kcx-qwerty). It's simpler and shows more of how you can organize your xkb files.

**Comment by iandoug** [comment]
Thanks. I was going to ask about the OTHER files ... base.* and evdev.* 

I see you have the two evdev files but they do not look like the regular evdev.lst and evdev.xml ... if I add entries to the default ones, they will get overwritten when xkb updates. Don't you need custom entries for your custom layout?

I was discussing these issues with someone else, he said that not all desktops pick up the private configs ... I use KDE.

Thanks, Ian

**Comment by james-orcales** [comment]
With `evdev`, you can provide individual toggleable options in your layout.

`evdev.xml` is what allows desktop environments (GNOME, KDE) to be aware of your custom layout and the options it provides. With this, you can select your layout in the DE's default settings app. (`gnome-control-center` for GNOME).

I have no experience with KDE but I assume it should work the same as GNOME when it comes to parsing xkb files. Check out the [resources](https://github.com/amesaine/colejak#resources) section. Everything you need to know about xkb is in there.

**Comment by iandoug** [comment]
Thanks.
I am on X11.

"In the posts linked above, I describe how it's possible to have custom keyboard layouts in $HOME or /etc/xkb that will get picked up by libxkbcommon. This only works for the Wayland stack, the X stack doesn't use libxkbcommon. In this post I'll explain why it's unlikely this will ever happen in X. "
